### ISSUE TITLE
[bug] user class

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/dr_green#1]
Attention à l'orthographe :
public function setAdress($address)
doit s'écrire :
public function setAddress($address)
Il manque un D !

**Comment by Shadownest** [comment]
Pour setAdmin, vous pouvez vérifier que $admin est un booleen et n'enregistrer qu'un booleen dans la propriété admin ;)

**Comment by DoudouPike** [comment]
Fait. Merci. =)
