### ISSUE TITLE
[debug] user manager

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/dr_green#5]
Dans la méthode save() :
Lorsque vous vérifiez $_SESSION['user']['id'], vous DEVEZ vérifier si $_SESSION['user'] existe !
(utilisez isset)

**Comment by Shadownest** [comment]
Pareil pour la méthode remove()

**Comment by Shadownest** [comment]
Dans la méthode create()
Vous ne pouvez pas faire $id_user = $user->getId(); tant que user n'est pas inséré dans la db

**Comment by DoudouPike** [comment]
Corrigé. Merci.
