### ISSUE TITLE
[debug] product manager

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/dr_green#6]
Avant de vérifier la valeur dans $_SESSION['user']['admin'] vous devez vérifier que la case existe !
(utilisez isset)

**Comment by Shadownest** [comment]
Dans create(), il manque les paramètres (name, description, exerpt, etc...) et vous utilisez 		$id = $product->getId(); avec un produit pas entré en db.

**Comment by DoudouPike** [comment]
Corrigé. Merci !!
