### ISSUE TITLE
[debug] comment manager

### ISSUE THREAD

**Issue by Shadownest** [DoudouPike/dr_green#7]
Avant de vérifier la valeur dans $_SESSION['user']['admin'] vous devez vérifier que la case existe !
(utilisez isset)

**Comment by Shadownest** [comment]
create() manque de paramètres

**Comment by DoudouPike** [comment]
J'avais bêtement C/C les autres managers sans réfléchir à ce qu'on avait besoin.
J'ai donc effacé les fonctions inutiles, et les lignes comportant les erreurs sont supprimées.
